#!/bin/bash

source /usr/local/lib/db-backup/utils.sh

require validate-env

if [ $# != 0 ]; then
    exec "$@"
else
    require_env DB_TYPE DB_HOST DB_DATABASE DB_USER DB_PASSWORD
    validate_env_opts DB_TYPE mysql mariadb postgresql

    echo "$DB_BACKUP_CRON_SCHEDULE db-backup >> /var/log/db-backup.log" | crontab -u "$DB_BACKUP_USER" -

    exec crond -fl 2
fi
