version: "2.2"
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres:/var/lib/postgresql/data

  db-backup:
    image: sunasteriskrns/db-backup
    restart: always
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=test
      - DB_USER=test
      - DB_PASSWORD=secret
      - DB_BACKUP_MAX_FILES=10
    volumes:
      - /data/backup:/data/backup

volumes:
  backup:
  postgres:
